# Log properties
logging:
  level.org.springframework: INFO
  level.com.dbg: DEBUG
  level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG
# Spring properties
spring:
  application:
    name: itutor
# MONGODB (MongoProperties)
  data:
    mongodb:
      uri: mongodb+srv://jiniguez:jig30592@cluster0-cknds.mongodb.net/test
# HTTP Server
server: 
  port: 5000