# Log properties
logging:
  level.org.springframework: INFO
  level.com.dbg: DEBUG
  level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG
# Spring properties
spring:
  application:
    name: itutor
# MONGODB (MongoProperties)
  data:
    mongodb:
      uri: mongodb://localhost/itutor
# HTTP Server
server: 
  port: 8081